In [1]:
print("Hello AI")

Hello AI

In [2]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.1
NumPy: 2.4.2

In [3]:
import matplotlib.pyplot as plt
import sklearn

print("Matplotlib OK")
print("Scikit-Learn:", sklearn.__version__)

Matplotlib OK
Scikit-Learn: 1.9.0

In [4]:
import pandas as pd

data = {
    "Name": ["Ansh","Rahul","Aman","Priya","Neha",
             "Karan","Riya","Arjun","Simran","Vikas",
             "Sneha","Rohit","Pooja","Yash","Nikita"],

    "CGPA": [8.5,7.8,9.1,8.0,7.5,
             8.9,9.3,6.8,8.2,7.1,
             9.0,8.4,7.9,8.7,9.2],

    "Attendance": [90,75,95,85,70,
                   92,98,65,88,72,
                   96,89,80,91,97],

    "Study_Hours": [4,2,5,3,2,
                    5,6,1,4,2,
                    5,4,3,5,6]
}

df = pd.DataFrame(data)

In [5]:
print (df)

      Name  CGPA  Attendance  Study_Hours
0     Ansh   8.5          90            4
1    Rahul   7.8          75            2
2     Aman   9.1          95            5
3    Priya   8.0          85            3
4     Neha   7.5          70            2
5    Karan   8.9          92            5
6     Riya   9.3          98            6
7    Arjun   6.8          65            1
8   Simran   8.2          88            4
9    Vikas   7.1          72            2
10   Sneha   9.0          96            5
11   Rohit   8.4          89            4
12   Pooja   7.9          80            3
13    Yash   8.7          91            5
14  Nikita   9.2          97            6

In [6]:
df.head()

    Name  CGPA  Attendance  Study_Hours
0   Ansh   8.5          90            4
1  Rahul   7.8          75            2
2   Aman   9.1          95            5
3  Priya   8.0          85            3
4   Neha   7.5          70            2

In [7]:
df.tail()

      Name  CGPA  Attendance  Study_Hours
10   Sneha   9.0          96            5
11   Rohit   8.4          89            4
12   Pooja   7.9          80            3
13    Yash   8.7          91            5
14  Nikita   9.2          97            6

In [8]:
df.shape

(15, 4)

In [9]:
df.columns

Index(['Name', 'CGPA', 'Attendance', 'Study_Hours'], dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         15 non-null     str
 1   CGPA         15 non-null     float64
 2   Attendance   15 non-null     int64
 3   Study_Hours  15 non-null     int64
dtypes: float64(1), int64(2), str(1)
memory usage: 612.0 bytes

In [11]:
df["CGPA"].mean()

np.float64(8.293333333333335)

In [12]:
df[["Name","CGPA"]]

      Name  CGPA
0     Ansh   8.5
1    Rahul   7.8
2     Aman   9.1
3    Priya   8.0
4     Neha   7.5
5    Karan   8.9
6     Riya   9.3
7    Arjun   6.8
8   Simran   8.2
9    Vikas   7.1
10   Sneha   9.0
11   Rohit   8.4
12   Pooja   7.9
13    Yash   8.7
14  Nikita   9.2

In [13]:
type(df[["Name"]])

pandas.DataFrame

In [14]:
df.describe()

            CGPA  Attendance  Study_Hours
count  15.000000   15.000000    15.000000
mean    8.293333   85.533333     3.800000
std     0.772257   10.635968     1.567528
min     6.800000   65.000000     1.000000
25%     7.850000   77.500000     2.500000
50%     8.400000   89.000000     4.000000
75%     8.950000   93.500000     5.000000
max     9.300000   98.000000     6.000000

In [15]:
df.to_csv('student_data.csv')

In [16]:
import os

print(os.getcwd())

c:\Users\hp\Desktop\JustONE\College\Python\Code\Pandas